### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by unickorn** [QuiverlyRivalry/CastleRaid-Core#4]
- [ ] !!!"New report command"
- [ ] Quest types
- [ ] Make it so players earn in-game money by chatting

Maybe:
If we get accepted we will have to change our economy system, we will be using nether games economy system, so we have to make our plugins work with them.
- [ ] Unsure, still waiting if we get merged
